#! /bin/sh

echo "run xcompile profile"
case ${TARGETARCH:-""} in

	amd64)
		export ARCHITECTURE=amd64
		export GCC_BUILD_TARGET=x86_64-linux-gnu
		export CARGO_BUILD_TARGET=x86_64-unknown-linux-gnu
		export PKG_CONFIG_ALLOW_CROSS=1
		export PKG_CONFIG_PATH=/usr/lib/${GCC_BUILD_TARGET}/pkgconfig/
		export XCOMPILER_TARGET=$(echo ${GCC_BUILD_TARGET} | tr '_' '-')
    		export CARGO_TARGET_$(echo ${CARGO_BUILD_TARGET} | tr '[:lower:]-' '[:upper:]_')_LINKER=${GCC_BUILD_TARGET}-gcc 
		;;
	
	arm64)
		export ARCHITECTURE=arm64
		export GCC_BUILD_TARGET=aarch64-linux-gnu
		export CARGO_BUILD_TARGET=aarch64-unknown-linux-gnu
		export PKG_CONFIG_ALLOW_CROSS=1
		export PKG_CONFIG_PATH=/usr/lib/${GCC_BUILD_TARGET}/pkgconfig/
		export XCOMPILER_TARGET=$(echo ${GCC_BUILD_TARGET} | tr '_' '-')
    		export CARGO_TARGET_$(echo ${CARGO_BUILD_TARGET} | tr '[:lower:]-' '[:upper:]_')_LINKER=${GCC_BUILD_TARGET}-gcc 
		;;

	*)
		:
		;;
esac
